### PR TITLE
Enabled for gnome-shell-3.22

### PR DESCRIPTION
**Pull request by wieczorek1990**

### CODE REVIEW

**Comment by sherl0cks** [comment]
@wieczorek1990 thanks for this fix

@vibou can you merge this? currently the master, as well as the build on https://extensions.gnome.org/extension/28/gtile/ do not support gnome 3.22 distros like Fedora 25

**Comment by Erikvv** [comment]
Works for me on Arch Linux with Wayland and gnome 3.22

**Comment by sboland687** [comment]
+1 on Fedora 25

**Comment by Vaesper** [comment]
Seems like a duplicate of #53

**Pull request closed without merging**
