### PR TITLE
Add full keybord control, presets for window positions, full settings…

### PR DESCRIPTION
**Pull request by scherepanov**
… through preferences dialog. Fixed couple of bugs here and there. Learn javascript/GTK+/gnome shell in process.
Add settings for bottom panel (top panel settings already there). I saw pull request for fixing top/bottom panel and panels on non-primary monitors, they should be obsolete now.
Fixed bug for top panels on non-primary monitors in second row of monitors.

### CODE REVIEW

**Comment by thet** [comment]
I love this feature, I'd love to have tiling presets!
Unfortunately Gnome doesn't seem to support an accelerator like "Super+Alt+Top+Left".

However, I have a different problem with your PR. It looks like the screen dimensions aren't correctly calculated. I have a HiDPI Laptop Screen with a 4k display, which is scaled down by the factor of 2 by Gnome.

This screenshot illustrates the problem very well:

screenshot from 2017-04-13 10-06-20

**Comment by thet** [comment]
Oh, that's not a problem with your PR. This HiDPI scaling issue also exists with main gTile without your PR applied.

**Comment by scherepanov** [comment]
I was able to reproduce problem with HiDPI window scaling.
There is a GTK API call to determine scaling factor, but seems to be it is not exposed in Java script API.
Fix would be simple, but so far I cannot find how to get scaling factor in Java script.

**Comment by scherepanov** [comment]
It is amazing - complete absence of any reasonable docs on Gnome
After some investigation I found how to get HiDPI Window scaling in Gnome, by looking at gnome-tweak-tool source code. Will issue a patch next week.

**Comment by cwh1te** [comment]
I'm currently running this branch on GNOME Shell 3.24.1 (Ubuntu 17.04) and am enjoying it with no bugs so far.
More semantic description on the added settings would be nice, but it didn't take much to figure them out.
Some of the changes in this PR seem unrelated to functionality, though. I'm wondering if this might get merged sooner without things like license and wording changes...

**Comment by scherepanov** [comment]
If you need more semantic description (i.e. help) - send me a text, I will include whatever you want.
Also, about changes unrelated to functionality. I have done some performance improvement, like unsubscribing from all events except single global hotkey, when gTile is not active. Otherwise it intercepts events like focus when not active, making whole Gnome less responsive.
When you say wording change, you want different license or you want change in license?
I have not clue when this branch will get merged.

**Comment by ElectricPrism** [comment]
I found this branch to be the most advanced and stable version of the plugin when reviewing the diff's.

Honestly if this doesn't get mainlined I would definately suggest renaming it and uploading to Gnome Extensions website so people can benefit from this. Shell Tiling is a space that many users can benefit on Gnome.

**Comment by scherepanov** [comment]
I hate multiplying plugins, it is very confusing to users.
OK, I will create new Gnome plugin (gTile+ ???) and will upload it to Gnome extensions web site.
If @vibou will show up and will continue to support this plugin, I will remove mine.

**Comment by lorendias** [comment]
We could try contactimg him via twitter
http://vibou.fr

He must be busy. 

Either way users would love this contribution and their workflows benefit

**Pull request merged**
